# Generated by Django 4.2.20 on 2025-04-21 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_product_category_alter_product_image'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowstockalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lowstockalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowstockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alerts', to='cart.product'),
        ),
        migrations.AlterField(
            model_name='lowstockalert',
            name='reorder_level',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
