# Generated by Django 4.2.20 on 2025-04-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FURNITURE_DECO', 'Furniture & Decor'), ('JEWELRY', 'Jewelry'), ('FINE_ART', 'Fine Art')], default='FURNITURE_DECO', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
