# Generated by Django 4.2.2 on 2025-04-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_product_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='external_id',
        ),
    ]
