# Generated by Django 4.2.2 on 2025-04-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_product_category_alter_product_image'),
        ('cart', '0010_product_product_id_delivery'),
    ]

    operations = [
    ]
