# Generated by Django 4.2.2 on 2025-04-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_merge_20250427_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
