# Generated by Django 4.2.20 on 2025-04-27 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auction_Combinatoire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combinatorial_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='combinatorialauction',
            name='products',
            field=models.ManyToManyField(related_name='combinatorial_auctions', to='Auction_Combinatoire.combinatorial_product'),
        ),
        migrations.AlterField(
            model_name='combinatorialbid',
            name='products',
            field=models.ManyToManyField(related_name='combinatorial_bids_product', to='Auction_Combinatoire.combinatorial_product'),
        ),
    ]
