# Generated by Django 5.1.6 on 2025-03-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode', models.CharField(choices=[('EDAHABIA', 'EDAHABIA'), ('CIB', 'CIB')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
