# Generated by Django 4.2.2 on 2025-04-20 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auction_English', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishauctionitem',
            name='bidder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='english_auction_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='englishauctionitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
